name:                cpp-printer-and-interpreter
version:             0.1.0.0
github:              "fypiskate/cpp-printer-and-interpreter"
license:             BSD3
author:              "Kate Mandroshchenko"
maintainer:          "ek.mandr@yandex.ru"
copyright:           "2020 Kate Mandroshchenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fypiskate/cpp-printer-and-interpreter#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cpp-printer-and-interpreter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cpp-printer-and-interpreter

tests:
  cpp-printer-and-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cpp-printer-and-interpreter
